//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.02 at 03:28:13 PM CET 
//


package se.lanteam.ws.gbgintraservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfGBCA003A_ErrorResponseLine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfGBCA003A_ErrorResponseLine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GBCA003A_ErrorResponseLine" type="{http://lanteam.se/ws/GbgIntraservice}GBCA003A_ErrorResponseLine" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfGBCA003A_ErrorResponseLine", propOrder = {
    "gbca003AErrorResponseLine"
})
public class ArrayOfGBCA003AErrorResponseLine {

    @XmlElement(name = "GBCA003A_ErrorResponseLine", nillable = true)
    protected List<GBCA003AErrorResponseLine> gbca003AErrorResponseLine;

    /**
     * Gets the value of the gbca003AErrorResponseLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gbca003AErrorResponseLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGBCA003AErrorResponseLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GBCA003AErrorResponseLine }
     * 
     * 
     */
    public List<GBCA003AErrorResponseLine> getGBCA003AErrorResponseLine() {
        if (gbca003AErrorResponseLine == null) {
            gbca003AErrorResponseLine = new ArrayList<GBCA003AErrorResponseLine>();
        }
        return this.gbca003AErrorResponseLine;
    }

}
