//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.02 at 04:20:45 PM CET 
//


package se.lanteam.ws.gbgintraservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="errorResponse" type="{http://lanteam.se/ws/GbgIntraservice}GBCA003A_ErrorResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errorResponse"
})
@XmlRootElement(name = "ErrorResponse")
public class ErrorResponse {

    @XmlElementRef(name = "errorResponse", namespace = "http://lanteam.se/ws/GbgIntraservice", type = JAXBElement.class, required = false)
    protected JAXBElement<GBCA003AErrorResponse> errorResponse;

    /**
     * Gets the value of the errorResponse property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GBCA003AErrorResponse }{@code >}
     *     
     */
    public JAXBElement<GBCA003AErrorResponse> getErrorResponse() {
        return errorResponse;
    }

    /**
     * Sets the value of the errorResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GBCA003AErrorResponse }{@code >}
     *     
     */
    public void setErrorResponse(JAXBElement<GBCA003AErrorResponse> value) {
        this.errorResponse = value;
    }

}
