//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.02 at 03:28:13 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://lanteam.se/ws/GbgIntraservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.lanteam.ws.gbgintraservice;
